version: '3.3'
services:
  wss-backend:
    image: q2kit/wss-backend:1.0
    container_name: wss-backend
    build: .
    ports:
      - 18080:80
    depends_on:
      - wss-db
      - wss-redis

  wss-db:
    image: postgres:14.0
    container_name: wss-db
    environment:
      POSTGRES_DB: wsservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  wss-redis:
    image: redis:6.2.6
    container_name: wss-redis
