# Generated by Django 4.0.7 on 2023-09-23 10:15

from django.db import migrations, models
import src.funks


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="secret_key",
            field=models.CharField(
                default=src.funks.secret_key_generator, editable=False, max_length=100
            ),
        ),
    ]
