# Generated by Django 4.0.7 on 2023-09-18 04:39

from django.db import migrations, models
import django.db.models.deletion
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=src.models.hex_uuid, editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='src.customer'),
        ),
    ]
